Ajax in Rails app
Vason-err/Rails-QNA pull request #4
Opened 2021-08-07 16:59 UTC by Vason-err

2021-08-09 07:22 UTC, VidgarVii requested changes

2021-08-09 07:22 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      @alert = "You can't update the question, because you aren't its author"
если действие не возможно по отсутствии прав на совершение данного действия, хорошо бы отдавать статус ответа 403 (Forbidden)

2021-08-09 07:22 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      @alert = "You can't update the question, because you aren't its author"
вложенные if сильно ухудшают читаемость кода и данный подход является опасным.
Данный экшен можно уменьшить до 2х строк
1 предусловие (авторизация) рендерм 403 если ресурс пытается обновить не автор
2 пытаемся обновить ресурс. Далее пусть работает js

для ответа тоже самое

2021-08-09 07:22 UTC, VidgarVii commented on spec/controllers/questions_controller_spec.rb
> +        end
данный тест ни как не тестирует обновление чужого ресурса.
контекст должен менять тело запроса

2021-08-09 07:22 UTC, VidgarVii commented on app/views/questions/index.html.slim
>    - @questions.each do |question|
1 перед итерацией нет смысла проверять наличие объектов в коллекции

2021-08-09 07:22 UTC, VidgarVii commented on app/views/questions/index.html.slim
>    - @questions.each do |question|
для рендеринга коллекция надо использовать render collection http://rusrails.ru/layouts-and-rendering-in-rails#rendering-kollektsiy
(уроки со 2 курса)

2021-08-09 07:22 UTC, VidgarVii commented on app/views/questions/new.html.slim
> += render "/shared/errors", resource: @question
предпочтительней использовать одинарные кавычки 
используй rubocop

2021-08-09 07:22 UTC, VidgarVii commented on app/views/questions/new.html.slim
> += render "/questions/form"
нет пустой строки (во многих файлах)
это обрыв файла

2021-08-09 07:22 UTC, VidgarVii commented on app/javascript/packs/answers.js
> +        let answerId = $(this).data('answerId');
answerId не переопределяется. Используй const вместо let

2021-08-09 07:22 UTC, VidgarVii commented on spec/features/questions/answers/create_spec.rb
> +  describe 'authenticated user', js: true do
это уже больше похоже на контекст.

2021-08-09 07:22 UTC, VidgarVii commented on spec/features/questions/answers/create_spec.rb
>  } do
у тебя папка answers почему вложена в папку questions.

2021-08-09 07:22 UTC, VidgarVii commented on app/controllers/answers_controller.rb
>    before_action :find_question, only: [:create]
уже много раз говорилось, что колбеки для 1 экшена не пишем.

2021-08-10 20:30 UTC, Vason-err commented
Довольно нелогично это здесь писать, но я так и не разобрался в чем баг приложения, скажите есть ли смысл переделать заново все, я просто перепробовал буквально все и не могу понять в чем именно ошибка, редачил и вьюхи и пытался найти ошибки в контроллере, в модели, я видимо просто не доконца разобрался как turbolinks работает, или где-то намудрил

2021-08-11 05:25 UTC, VidgarVii requested changes

2021-08-11 05:25 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    render status: :forbidden if !(current_user.author_of?(@question))
`render status: :forbidden unless current_user.author_of?(@question)`

2021-08-11 05:25 UTC, VidgarVii commented on spec/controllers/answers_controller_spec.rb
>        end
статус надо протестировать. в тестах вопроса тоже

2021-08-11 05:25 UTC, VidgarVii commented on spec/controllers/answers_controller_spec.rb
> +        expect { patch_update }.not_to change { answer.body }
а как тут понять что обновляется чужой ответ? судя по запросу идёт обновления собственного ответа. И статус тут будет 200

2021-08-11 05:25 UTC, VidgarVii commented on app/controllers/answers_controller.rb
>    before_action :find_question, only: [:create]
не исправил!

2021-08-11 05:25 UTC, VidgarVii commented on app/models/question.rb
> +  has_one :best_answer, class_name: 'Answer', dependent: :nullify
тут ассоциация объявлена не верно. Так как best_answer_id у тебя находится в таблице вопросов. То тут должен быть belongs_to.
Это  звучит как то странно. Вопрос принадлежит лучшему ответу. Но это будет работать...
По этому можно сделать куда проще.
Во первых вопросу не обязательно знать кто там лучший, а кто нет.
Можно просто добавить булевое поле в таблицу ответов, которое и будет определять лучший он или нет.

2021-08-12 06:07 UTC, VidgarVii commented on app/models/answer.rb
> +  end
Это тоже самое 
- Петя ты лучший?
- Подожди я у Васи спрошу.
данное решение приводит к лишним запросам в БД, который можно избежать.
И зачем вопросу вообще содержать данные об ответах?

прочитай еще раз коммент https://github.com/Vason-err/Rails-QNA/pull/4#discussion_r686500458

2021-08-13 08:26 UTC, VidgarVii requested changes

2021-08-13 08:26 UTC, VidgarVii commented on spec/models/answer_spec.rb
> +  describe 'best answer' do
тут мы тестируем инстанс метод.
для методов принято есть соглашение по описанию describe
`describe '#mark_as_best'`

2021-08-13 08:26 UTC, VidgarVii commented on spec/models/answer_spec.rb
> +    end
используй рубокоп
https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/MultipleExpectations

2021-08-13 08:26 UTC, VidgarVii commented on spec/models/answer_spec.rb
> +      expect(answer).to_not be_best
при создании объекта можно явно прописать что ответ не является лучший. Это тестировать это не надо. 
А то что после вызова метода mark_as_best меняется значение, то хорошо бы использовать матчер change

2021-08-13 08:26 UTC, VidgarVii commented on spec/models/answer_spec.rb
> +      best_answer = create(:answer, question: question, best: true)
все переменные объявляем в блоке let

2021-08-13 08:26 UTC, VidgarVii commented on spec/models/answer_spec.rb
> +  end
можно сразу создать 2 ответа для 1 вопроса. Один из них пусть будет лучший
И 1 левые ответ которые будет the best
Вызови метод mark_as_best для 1 ответа
И проверь результаты всех ответов

2021-08-13 14:38 UTC, merged