Active storage
Vason-err/Rails-QNA pull request #5
Opened 2021-08-16 21:01 UTC by Vason-err

2021-08-16 21:08 UTC, Vason-err commented
Где-то ошибка в тестах, при создании файла, когда в фабрике создается вопрос или ответ с файлами, то ошибок нет, но при этом потом при тестировании файла просто нет, сначала думал, что ошибка в пути, просто он ее не показывает, использовал также Rack::Test::UploadedFile.new, то же самое ошибок нет, как и самого файла, работает все прекрасно, ошибка только в тестовой среде, пробовал все что нашел, ничего не помогло

2021-08-17 18:29 UTC, VidgarVii requested changes

2021-08-17 18:29 UTC, VidgarVii commented on app/controllers/files_controller.rb
> +    head(:forbidden) unless current_user.author_of?(@file.record)
это ни как не защитит от удаления файла левым пользователем.

2021-08-17 18:29 UTC, VidgarVii commented on spec/controllers/files_cotroller_spec.rb
> +    let(:delete_destroy) { delete :destroy, params: { id: question.files.first }, format: :js }
почему в id ты передаёшь оъект файла?

2021-08-17 20:49 UTC, Vason-err commented on spec/factories/answers.rb
> +          io: File.open(Rails.root.join('spec', 'rails_helper.rb')),
Пришлось сделать так, по-другому просто никак не работает, пробовал абсолютно все, видимо на рельсах выше 6 какие-то проблемы c fixture_file_upload либо Rack::Test::UploadedFile.new(), либо я глупый просто и что-то не так сделал

2021-08-18 14:19 UTC, merged