Nested forms and polymorphics
Vason-err/Rails-QNA pull request #6
Opened 2021-08-22 17:28 UTC by Vason-err

2021-08-23 18:40 UTC, VidgarVii requested changes

2021-08-23 18:40 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :body, files: [], links_attributes: [:name, :url, :_destroy], reward_attributes: %i[title file])
за такие длинные строки 100% будет ругаться рубокоп

2021-08-23 18:40 UTC, VidgarVii commented on app/models/answer.rb
> +      question.reward&.update!(user_id: user_id)
вот этот момент (question.reward) надо протестировать

2021-08-23 18:40 UTC, VidgarVii commented on app/views/questions/show.html.slim
> +  -if @question&.links.present?
https://msp-greg.github.io/rubocop/RuboCop/Cop/Style/SafeNavigation.html

2021-08-23 18:40 UTC, VidgarVii commented on spec/features/answers/add_links_spec.rb
> +feature 'user can add links to answer', %q{
это можно протестировать сразу при создании ответа/вопроса.
Этим мы сократим время прохождения тестов.

2021-08-23 18:40 UTC, VidgarVii commented on spec/features/rewards/index_spec.rb
> +    rewards.each do |reward|
each плохая практика использовать в тесах. если что-то упадёт придется долго разбираться что именно.
Лучше создать разные награды и каждую отдельно проверить
rubocop-rspec!

2021-08-23 18:40 UTC, VidgarVii commented on app/models/answer.rb
> +      question.reward&.update!(user_id: user_id)
нет фича тестов

2021-08-23 18:40 UTC, VidgarVii commented on app/models/answer.rb
> +      question.reward&.update!(user_id: user_id)
при выборе лучшего ответа, ответ не становится 1м в списке

2021-08-24 14:40 UTC, Vason-err commented on spec/features/rewards/index_spec.rb
> +    rewards.each do |reward|
Исправил

2021-08-24 14:40 UTC, Vason-err commented on spec/features/answers/add_links_spec.rb
> +feature 'user can add links to answer', %q{
Исправил

2021-08-24 14:44 UTC, Vason-err commented on app/models/answer.rb
> +      question.reward&.update!(user_id: user_id)
Вы имеете ввиду написать тест на проверку нахождения лучшего 1-ым в списке, или что не работает при запуске приложения, потому что при запуске приложения вроде все работает, лично тестил, question.reward протестирован в тестах модели, а вот как написать на это feature test не очень понимаю если често это мне надо делать как два контеста, или просто для одного или хватит просто проверить что награда идет самому же автору

2021-08-24 14:44 UTC, Vason-err commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :body, files: [], links_attributes: [:name, :url, :_destroy], reward_attributes: %i[title file])
исправил

2021-08-25 09:52 UTC, merged